name: Docker Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest  

    - name: Set global environment variables
      run: |
        echo "PKG_CONFIG_PATH=/root/compiled/lib/pkgconfig" >> $GITHUB_ENV
        echo "GOPATH=/go" >> $GITHUB_ENV

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build minimal livepeer distributable 
      run: |
        # We publish two tags for each build:
        # livepeer/go-livepeer:BRANCH_NAME and livepeer/go-livepeer:VERSION_STRING. Both are useful
        # to pull from in different contexts.
        # Our Docker tag name should be our branch name with just alphanums
        BRANCH_TAG=$(echo $GHA_REF | sed 's/refs\/heads\///' | sed 's/\//-/g' | tr -cd '[:alnum:]_-')
        VERSION_TAG=$(./print_version.sh)
        docker buildx build \
          --platform=linux/arm64 \
          -t livepeer/go-livepeer:${BRANCH_TAG} \
          -t livepeer/go-livepeer:${VERSION_TAG} \
          --push \
          --cache-from type=registry,ref=livepeerci/go-livepeer-build-cache \
          --cache-to   type=registry,ref=livepeerci/go-livepeer-build-cache,mode=max \
          -f docker/Dockerfile.build .

      env:
        GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
