name: Linux Build
on: push
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
    - name: Prepare
      id: prep
      run: |
        BRANCH_TAG=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/\//-/g' | tr -cd '[:alnum:]_-') 
        VERSION_TAG=$(./print_version.sh)
        IMAGE="livepeer/go-livepeer"
        BUILDER_IMAGE="livepeerci/build:latest"
        echo ::set-output name=builder_tagged_image::${BUILDER_IMAGE}
        echo ::set-output name=branch_tagged_image::${IMAGE}:${BRANCH_TAG}
        echo ::set-output name=version_tagged_image::${IMAGE}:${VERSION_TAG}
        echo ::set-output name=branch_tag::${BRANCH_TAG}
        echo ::set-output name=version_tag::${VERSION_TAG}
      env: 
        GITHUB_REF: ${{ github.ref }}
    - name: Setup Docker Buildx
      id: buildx
      # Use the action from the master, as we've seen some inconsistencies with @v1
      # Issue: https://github.com/docker/build-push-action/issues/286
      uses: docker/setup-buildx-action@master
      with:
        install: true
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build builder
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: docker/Dockerfile.build-linux
        target: builder
        push: true
        tags: ${{ steps.prep.outputs.builder_tagged_image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
    - name: Build go-livepeer
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: docker/Dockerfile.build-linux
        target: livepeer
        push: true
        tags: ${{ steps.prep.outputs.branch_tagged_image }},${{ steps.prep.outputs.version_tagged_image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  test:
    runs-on: ubuntu-16.04
    needs: build
    container:
      image: livepeerci/build:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    defaults:
      run:
        working-directory: /build
    steps:
    - name: Set global environment variables
      run: |
        echo "PKG_CONFIG_PATH=/root/compiled/lib/pkgconfig" >> $GITHUB_ENV
        echo "GOPATH=/go" >> $GITHUB_ENV
    - name: Lint
      run: golangci-lint --disable-all --enable=gofmt --enable=vet --enable=golint --deadline=4m run pm verification
    - name: Run unit tests
      run: /bin/bash test.sh
    - name: Upload build
      run: ./upload_build.sh
      env:
        GITHUB_REF: ${{ github.ref }}
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
    - name: Notify new build upload
      run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
