name: Linux Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: [ubuntu-18.04]
            arch: amd64
          - os: [self-hosted, Linux, ARM64]
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.5' 
    - name: Cache go modules
      id: cache-go-mod
      uses: actions/cache@v2.1.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.arch }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-go-
    - name: Cache ffmpeg
      id: cache-ffmpeg
      uses: actions/cache@v2.1.5
      with:
        path: ~/compiled
        key: ${{ runner.os }}-${{ matrix.arch }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-ffmpeg
    - name: Cache binaries
      uses: actions/cache@v2.1.5
      with:
        path: ~/build
        key: ${{ runner.os }}-${{ matrix.arch }}-binaries-${{ github.sha }}
    - name: Install dependencies
      run: |
        sudo apt-get update \
          && sudo apt-get install -y software-properties-common curl apt-transport-https \
          && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 15CF4D18AF4F7421 \
          && sudo add-apt-repository "deb [arch=${{ matrix.arch }}] http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main" \
          && sudo apt-get update \
          && sudo apt-get -y install clang-8 clang-tools-8 build-essential pkg-config autoconf git python protobuf-compiler

        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-8 30 \
          && sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 30
    - name: Install go modules
      if: steps.cache-go-mod.outputs.cache-hit != 'true'
      run: go mod download
    - name: Install ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: ./install_ffmpeg.sh
    - name: Build binaries
      run: |
        export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
        ./ci_env.sh make
        rm -rf ~/build && mkdir ~/build && mv livepeer* ~/build/
      env:
        GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
  test:
    strategy:
      matrix:
        include:
          - os: [ubuntu-18.04]
            arch: amd64
          - os: [self-hosted, Linux, ARM64]
            arch: arm64
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          lfs: 'true'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - name: Cache go modules
        id: cache-go-mod
        uses: actions/cache@v2.1.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-go-
      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v2.1.5
        with:
          path: ~/compiled
          key: ${{ runner.os }}-${{ matrix.arch }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-ffmpeg
      - name: Lint
        run: |
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
          golangci-lint run --disable-all --enable=gofmt --enable=vet --enable=golint --deadline=4m pm verification
      - name: Run tests
        shell: bash
        run: |
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          ./test.sh
  upload:
    strategy:
      matrix:
        include:
          - os: [ubuntu-18.04]
            arch: amd64
          - os: [self-hosted, Linux, ARM64]
            arch: arm64
    runs-on: ${{ matrix.os }}
    needs: [build, test]
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Needed for commands that depend on git tags
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache binaries
        uses: actions/cache@v2.1.5
        with:
          path: ~/build
          key: ${{ runner.os }}-${{ matrix.arch }}-binaries-${{ github.sha }}
      - name: Upload build
        run: cp ~/build/* . && ./upload_build.sh
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
