name: Trigger test suite

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          lfs: 'true'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Install protobuf
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@v1.3.5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Cache go modules
        id: cache-go-mod
        uses: actions/cache@v2.1.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v2.1.5
        with:
          path: ~/compiled
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-ffmpeg

      - name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Compile proto files
        run: |
          protoc --version
          touch net/lp_rpc.proto net/redeemer.proto
          make net/lp_rpc.pb.go net/redeemer.pb.go
          git diff --exit-code

      - name: Lint
        run: |
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
          golangci-lint run --disable-all --enable=gofmt --enable=vet --enable=golint --deadline=4m pm verification

      - name: Run tests
        shell: bash
        run: |
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          ./test.sh
